CAMERA_ENABLED = True

MOTOR_FRONT_LEFT = 4
MOTOR_FRONT_RIGHT = 17
MOTOR_BACK_RIGHT = 27
MOTOR_BACK_LEFT = 22

MOTOR_CALIBRATION = {
    MOTOR_FRONT_LEFT: 0,
    MOTOR_FRONT_RIGHT: 0,
    MOTOR_BACK_RIGHT: 0,
    MOTOR_BACK_LEFT: 0,
}

DEFAULT_HOST = 'raspberrypi'
DEFAULT_PORT = 7777
